apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: k4vwrt52e-go 
  janus-idp.io/tekton: k4vwrt52e-go
  backstage.io/kubernetes-id: k4vwrt52e-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k4vwrt52e-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml